### ISSUE TITLE
Remove Massless Remnant Evolutions

### ISSUE THREAD

**Issue by nbungart1999** [aCOSMIC/aCOSMIC#553]
I'm trying to evolve WD binary systems such that they still end up in a binary with neither of the stars being a massless remnant. I thought it would work by setting both final_kstar1 and 2 to [10,11,12] to force it to evolve only into those 3 types. However when running I still end up with a good number of massless remnants, is there a way to stop this?

**Comment by katiebreivik** [comment]
Hey @pan1c22  -- can you copy your command line call to cosmic-pop to help diagnose the problem? (sorry for the slow response!!)

**Comment by katiebreivik** [comment]
@pan1c22 : I'm going to close this in the spirit of cleanup, but feel free to reopen if you get back to this.
