### ISSUE TITLE
Wind prescription for very massive main-sequence stars

### ISSUE THREAD

**Issue by poojanagrawal** [aCOSMIC/aCOSMIC#554]
Hi, I have been recently looking into mlwind.f in COSMIC and there seems to be an issue in the choice of Teff for Vink et al. (2001) winds. 
For very massive stars on main-sequence with Teff > 50000 K, the code should use Vink et al. (2001) winds (for windflag 2 and 3) if the conditions for LBV winds are not met. It, however, seems to be using Nieuwenhuijzen & de Jager (1990) winds (as L>4000Lsun).

**Comment by katiebreivik** [comment]
Thanks for flagging this @poojanagrawal! Sorry for the slow response time!

**Comment by katiebreivik** [comment]
Hey @poojanagrawal  -- I assume that your last PR fixes this issue, but can you confirm that this is the case?

**Comment by katiebreivik** [comment]
I think this is all set from the previous release
