### ISSUE TITLE
Orbital sample error in renzo19

### ISSUE THREAD

**Issue by elenagonzalez870** [aCOSMIC/aCOSMIC#558]
When trying to sample orbits using the Renzo19 model, there's an error (image attached). I believe it is fixed by setting b=log10_porb_max  to b=log10_porb_max[ind_massive] in the independent.py file 
<img width="772" alt="Screen Shot 2022-06-10 at 10 41 28 AM" src="https://user-images.githubusercontent.com/52000594/173138577-79ae0e8f-9659-4af8-8877-acc5f0b5a08a.png">

**Comment by katiebreivik** [comment]
Thank you for opening this @elenagonzalez870 ! 

I'd love to help make sure that you maintain credit for finding the bug and a fix! Do you mind submitting a pull request with these changes?

**Comment by katiebreivik** [comment]
this is now fixed here: https://github.com/COSMIC-PopSynth/COSMIC/pull/563
