### ISSUE TITLE
Results in example do not match current version

### ISSUE THREAD

**Issue by Tohuvavohu** [aCOSMIC/aCOSMIC#577]
Trying to run through the examples shown here: https://cosmic-popsynth.github.io/docs/stable/examples/index.html
with  Version: 3.4.7 produces different results than shown in the example for both of the GW150914 and GW170817-like binaries.

Since I'm a noob,I thought i was doing something wrong, and not that the results (wrt stellar type) could be so sensitive to the code version.
Might be worthwhile to rerun the examples to match the current version release.

**Comment by katiebreivik** [comment]
thanks for flagging @Tohuvavohu  -- should be all up to date with the latest release here: https://cosmic-popsynth.github.io/docs/stable/
