### ISSUE TITLE
Frame of reference for natal kicks

### ISSUE THREAD

**Issue by ghost** [aCOSMIC/aCOSMIC#621]
Hi,
In the documentation & kick table outputs the angles theta & phi that describe the natal kick are azimuthal & polar angles of explosion (in the frame of the exploding star) respectively. 
I wanted to know more about this frame of reference - I am I right in thinking phi, the polar angle, is measured between the polar axis of the exploding star & the orbital plane? (e.g. Y - XZ)
For theta, the azimuthal angle, is this measured between the direction of orbital motion and the center of mass, or vice versa? 
I hope the above makes sense, I've attached a rough schematic which may be useful,

Thanks!
Cordelia 
![Picture2](https://github.com/COSMIC-PopSynth/COSMIC/assets/142584303/6d82ca3c-2eff-4b51-9d97-194e222ce66a)
![Picture1](https://github.com/COSMIC-PopSynth/COSMIC/assets/142584303/76924510-51cb-4a07-ae89-d174d77baf71)

**Comment by TomWagg** [comment]
Hi Cordelia,

Yes I believe you have the definitions correct and for theta it's relative to the centre of mass, i.e. theta=phi=0 points at the companion star 🙂 (Though @katiebreivik please correct me if I'm wrong)

As some "proof": recently I was playing around with finding systems in COSMIC where the compact object is kicked directly into its companion (was thinking about TZOs) and plotted theta/phi for those systems. You can see those with values close theta=phi=0 tend to hit their companion (so I mark them as TZO candidates) and the outliers are just those with really small separations.
![image](https://github.com/COSMIC-PopSynth/COSMIC/assets/21990332/533ddc7f-3ff9-4852-a39f-fd60a68c0a0e)

Hope this helps!

**Comment by katiebreivik** [comment]
Hello @cdashwoodbrown! So sorry that this is a very belated update. @TomWagg  is 100% correct here.

**Comment by katiebreivik** [comment]
closing this for now -- feel free to re-open if needed!
