### ISSUE TITLE
Memory leak in new build

### ISSUE THREAD

**Issue by Dsantra92** [aCOSMIC/aCOSMIC#641]
I was using the latest commit for COSMIC-POP and noticed that the memory occupied by the program is steadily increasing and is later terminated by the OS as soon as the RAM and swap is filled.

**Comment by katiebreivik** [comment]
Thanks for the heads up! Will definitely look into this.

**Comment by katiebreivik** [comment]
Hey @Dsantra92 Can you supply your command-line call to `cosmic-pop`? I've been running a simple example locally with the following call:
`> cosmic-pop --inifile Params.ini --final-kstar1 11 --final-kstar2 11 --metallicity 0.014 --Nstep 10000 --Niter 500000 --nproc 3`
and found that things are working as I expect them to be.

**Comment by Dsantra92** [comment]
Thanks for the quick response. I have a similar command line instruction.

```cosmic-pop --final-kstar1 13 14 --final-kstar2 13 14 --inifile Params.ini --Nstep 1000 --Niter 10000 ```

I opened this issue because before the meson build system, I could run around 10k samples per step without any memory issue, with the latest commit I can barely run 2000 per step. It might be a problem with my local, will try it out in another system and let you know.

**Comment by katiebreivik** [comment]
closing this for now -- feel free to re-open if needed!
