### ISSUE TITLE
Kick implementation peculiarity: why does secondary star ejection velocity depend on natal kick strength?

### ISSUE THREAD

**Issue by TomWagg** [aCOSMIC/aCOSMIC#675]
I was chatting to @katiebreivik about this and we thought it would be great to hear what @michaelzevin thinks about this :)

My intuition is that when a primary star receives a natal kick that disrupts the binary, the secondary star is ejected with close to its orbital velocity. However, it seems in COSMIC that the ejection velocity of the secondary is very dependent on the natal kick that the primary receives.

As an example, I ran the same 20+15 Msol binary (P=100d, ecc=0, Z=0.02) 5000 times to get it to sample different natal kicks and found the following distribution of ejection velocities.
![image](https://github.com/user-attachments/assets/3d4a0f8a-0178-47cd-a3d1-26c4af686988)

The peak of the distribution lines up with the orbital velocity of the secondary but there's a large spread of different values.

Also if I re-run the same code but with extremely ridiculous kicks (`sigma=10000`) then the ejection velocities _also_ increase a lot

![image](https://github.com/user-attachments/assets/eadb0517-a614-47c3-8ce3-104e0affaad2)

Does this behaviour make sense? My guess would have been that the ejection velocity isn't affected by the natal kick significantly.

**Comment by michaelzevin** [comment]
Hey @TomWagg. I haven't checked this explicitly in the code yet, but could it be possible that the component's velocity when disrupted is relative to the center of mass of the system? If so, I think it would make sense that there is a correlation between the primary and secondary velocities upon disruption.

**Comment by mathren** [comment]
Thanks for the quick reply @michaelzevin! I'm just chiming in to say @TomWagg is looking into this, but if that is the case, it's a bit of a weird thing for COSMIC to report in my opinion. The kick causes the COM of the binary frame to _not_ be an inertial frame, so it's a weird choice instead of sticking with the frame of the COM at binary formation...

**Comment by michaelzevin** [comment]
Agree that it is a poor choice and should be fixed in a PR if it is the case. Just a hunch given the observed behavior, but we can certainly change it to provide something more physical.

**Comment by katiebreivik** [comment]
> Thanks for the quick reply @michaelzevin! I'm just chiming in to say @TomWagg is looking into this, but if that is the case, it's a bit of a weird thing for COSMIC to report in my opinion. The kick causes the COM of the binary frame to _not_ be an inertial frame, so it's a weird choice instead of sticking with the frame of the COM at binary formation...

One quick thing to consider though, is that I think the frame needs to be updated depending on the first kick right? If we only keep track relative to the COM at the _formation_ of the binary, then a primary kick will make the future velocities look wonky as well. Does it make sense to update to the new binary COM at each stage? @TomWagg  would this bork things out on cogsworth's side?

**Comment by TomWagg** [comment]
Yeah agreed, I think it should be relative to the pre-SN COM, which is different once you reach the second supernova. That'll be fine for cogsworth I think.

**Comment by TomWagg** [comment]
Kiel & Hurley at least claim that Eq. 18-20 are the "final velocities of the two stars in the pre-SN CofM reference frame", which seems to be what we want. But the confusing thing is that Eq. 12 and 13 account for V_S' (the CofM velocity _after_ the supernova, instead of V_S), so wouldn't that make it relative to the post-SN CofM frame?

Based on that I tried subtracting the V_S' terms from the final component velocities using the values reported in the bpp table at the moment of SN1, but that doesn't seem to be doing the right thing - in particular the Z component is nonzero still after the subtraction, but it _should_ be zero. Is the COSMIC implementation different from Kiel & Hurley in this?

**Comment by TomWagg** [comment]
Just to update, it definitely seems like something strange is going on with the Kiel & Hurley prescription - I've just opened a PR that implements the work of Pfahl+2002 which seems to give much more physically intuitive answers (and is in line with COMPAS and binary_c)
